
variables:
  MONO_VERSION: 5_18_1
  XCODE_VERSION: 10.2.1

jobs:
  - job: build_windows
    pool:
      vmImage: vs2017-win2016
    steps:
      - powershell: .\build.ps1
  - job: build_macos
    pool:
      vmImage: macos-10.13
    steps:
      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
      - powershell: ./build.ps1
  - job: build_linux
    pool:
      vmImage: ubuntu-16.04
    steps:
      - powershell: ./build.ps1
